name: Test Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: KarasuLab Mod Releaser Test
        uses: ./
        with:
          modrinth_project_id: ${{ vars.MODRINTH_PROJECT_ID }}
          modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge_project_id: ${{ vars.CURSEFORGE_PROJECT_ID }}
          curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
